---


- name: Create nginx directory
  file:
    path: "{{ nginx_path }}"
    state: directory
    mode: "0755"

- name: Create nginx conf file
  template: 
    src: "{{ nginx_conf_src }}"
    dest: "{{ nginx_path }}/nginx.conf"

- name: Create nginx docker-compose file
  template: 
    src: "{{ docker_compose_src }}"
    dest: "{{ nginx_path }}/docker-compose.yml"

- name: Install certbot and nginx plugin
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - certbot
    - python3-certbot-nginx

- name: Generate SSL certificate with certbot
  command: certbot certonly --standalone -d gitlab-pfw.pro -d www.gitlab-pfw.pro --agree-tos --email pg.flauw@gmail.com --non-interactive -vv
  args:
    creates: "{{ ssl_certificate_path }}"

- name: Ensure certbot renews certificates automatically
  cron:
    name: "Renew Let's Encrypt certificates"
    minute: "0"
    hour: "3"
    job: "/usr/bin/certbot renew --quiet"
    state: present

- name: Create and start nginx
  command: docker compose up -d
  args:
    chdir: "{{ nginx_path }}"


