---


- name: Create Jenkins directory
  file:
    path: "{{ jenkins_path }}"
    state: directory
    mode: "0755"

- name: Create Jenkins docker compose file 
  template: 
    src: "{{  docker_compose_src }}"
    dest: "{{ jenkins_path }}/docker-compose.yml"

- name: Create and start Jenkins
  command: docker compose up -d
  args:
    chdir: "{{ jenkins_path }}"